const fsP = require("fs/promises");

// async function readMyFile() {
//   try {
//     let contents = await fsP.readFile("myFile.txt", "utf8");
//     console.log("file contents", contents);
//   } catch (err) {
//     process.exit(1);
//   }
// }
const fsP = require("fs/promises");
/** Express app for auth-api. */
const express = require("express");

const app = express();

var mongoose = require("mongoose");
var faker = require("faker");
var path = require("path");
var fakerModel = require("./models/user");
// Initializing our variables with a different random data each time it is run
var randomName = faker.name.findName(); // Generates a random name
var randomEmail = faker.internet.email(); // Generates a random email
var randomProduct = faker.commerce.productName(); // Generates a random product name
var randomCompany = faker.company.companyName(); // Will give back a random company name
var randomCard = faker.helpers.createCard(); // It's output is a random contact card containing many properties

mongoose
.connect("mongodb://localhost:27017/fakedata", { useNewUrlParser: true })
.then(() => console.log("connected to db"))
.catch((error) => console.log("connection error", error));
app.set("view engine", "ejs");
app.set("views", path.resolve(__dirname, "views"));

app.get("/", (req, res) => {
	fakerModel.find((err, data) => {
		if (err) {
			console.log(err);
		} else if (data) {
			res.render("home", { data: data });
		} else {
			res.render("home", { data: {} });
		}
	});
});

// Return each data generated to the variables below and save all of them
// This will  be done ten times due to the for loop
// You can add the number of data to be generated by changing the value
app.post("/", (req, res) => {
	for (var i = 0; i < 10; i++) {
		var fakee = new fakerModel({
			firstname: faker.name.firstName(),
			lastname: faker.name.lastName(),
			phonenumber: faker.phone.phoneNumber(),
			city: faker.address.city(),
			state: faker.address.state(),
			country: faker.address.country(),
		});
		fakee.save((err, data) => {
			if (err) {
				console.log(err);
			}
		});
	}
	res.redirect("/");
});


// Iteration
// This code runs twenty times
// It produces each time different data
for (i = 0; i < 20; i++) {
	console.log(randomName); // Outputs a random name
	console.log(randomEmail); // Outputs a random email
	console.log(randomProduct); // Outputs the random product name generated
	console.log(randomCompany); // Produces a random company name
	console.log(randomCard); // Gives back a random card
	console.log(faker.date.past()); // Generates a random past date
}
const randomName = "THIS WILL GO IN THE FILE!";

async function writeOutput() {
  try {
    await fsP.writeFile("./output.txt", randomName, "utf8");
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
  console.log("Successfully wrote to file!");
}


writeOutput()